"""Add case status and doctor tracking to AnalysisReport

Revision ID: 1d8aeafb0f8f
Revises: c27febda1dc0
Create Date: 2025-12-20 13:41:44.924227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d8aeafb0f8f'
down_revision: Union[str, Sequence[str], None] = 'c27febda1dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.add_column('analysis_reports', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.add_column('analysis_reports', sa.Column('review_status', sa.String(), nullable=False))
    op.add_column('analysis_reports', sa.Column('doctor_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'analysis_reports', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_reports', type_='foreignkey')
    op.drop_column('analysis_reports', 'doctor_active')
    op.drop_column('analysis_reports', 'review_status')
    op.drop_column('analysis_reports', 'doctor_id')
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], name=op.f('chat_messages_report_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('chat_messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###
