"""doctor profile integrity and avatar_url

Revision ID: 2e28fad97467
Revises: 0d38e3f02e34
Create Date: 2025-12-21 13:46:00.426523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e28fad97467'
down_revision: Union[str, Sequence[str], None] = '0d38e3f02e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('avatar_url', sa.String(), nullable=False))
    op.alter_column('doctor_profiles', 'clinic_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('doctor_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('doctor_profiles', 'clinic_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('doctor_profiles', 'avatar_url')
    # ### end Alembic commands ###
